@name("text payload")
GET http://httpbin.org/robots.txt
> {%
class TestPayload(unittest.TestCase):
    def test_status(self):
        self.assertEqual(200, client.response.status_code)

    def test_content_type(self):
        self.assertEqual("application/json", client.response.headers.get('content-type'))

client.properties.set("outputval", client.response.text)
%} python
