@name('xml payload')
POST "https://httpbin.org/post"
"Content-Type" : "application/xml"
data(
"""
<?xml version='1.0' encoding='us-ascii'?>

<!--  A SAMPLE set of slides  -->

<slideshow
    title="Sample Slide Show"
    date="Date of publication"
    author="Yours Truly"
    >

    <!-- TITLE SLIDE -->
    <slide type="all">
        <title>Wake up to WonderWidgets!</title>
    </slide>
"""
// you can define anything here
/*
"""
    <slide type="all">
    <title>this is commented and, easily taken back</title>
    </slide>
"""
*/

"""
    <!-- OVERVIEW -->
    <slide type="all">
        <title>Overview</title>
        <item>Why <em>WonderWidgets</em> are great</item>
        <item/>
        <item>Who <em>buys</em> WonderWidgets</item>
    </slide>

</slideshow>
"""
)
