POST 'https://req.dothttp.dev'
data('simple string')

POST 'https://req.dothttp.dev'
data('simple'' string')

POST 'https://req.dothttp.dev'
data('simple' ' string')

POST 'https://req.dothttp.dev'
data('''simple string''')


POST 'https://req.dothttp.dev'
data('''simple ''' 'string')


POST 'https://req.dothttp.dev'
data('''simple ''' '''string''')


POST 'https://req.dothttp.dev'
data('simple' ' triple' ' break' ' string')
