@name(base)
GET ""
basicauth("username", "password")
header1: headervalue1

@name(sub): base
GET "https://httpbin.org/basic-auth/username/password"
header2: headervalue2

@name(sub2): sub
GET "https://httpbin.org/basic-auth/username/password"
header3: headervalue3

@name(sub3): unknown
GET "https://httpbin.org/basic-auth/username/password"
header3: headervalue3


@name(digest)
GET "https://httpbin.org/digest-auth/20202/username/password/md5"
digestauth("username", "password")
header4: headervalue4

@name("use digest auth"): digest
GET "https://httpbin.org/digest-auth/20202/username/password/md5"

@name("use digest auth post"): digest
POST "https://httpbin.org/digest-auth/20202/username/password/md5"


@name(query)
GET "https://httpbin.org/digest-auth/20202/username/password/md5"
? ram = raju

@name("query2"): query
POST "https://httpbin.org/digest-auth/20202/username/password/md5"

