@name(base)
GET ""
basicauth("username", "password")
header1: headervalue1

@name(sub): base
GET "http://localhost:8000/basic-auth/username/password"
header2: headervalue2

@name(sub2): sub
GET "http://localhost:8000/basic-auth/username/password"
header3: headervalue3

@name(sub3): unknown
GET "http://localhost:8000/basic-auth/username/password"
header3: headervalue3


@name(digest)
GET "http://localhost:8000/digest-auth/20202/username/password/md5"
digestauth("username", "password")
header4: headervalue4

@name("use digest auth"): digest
GET "http://localhost:8000/digest-auth/20202/username/password/md5"

@name("use digest auth post"): digest
POST "http://localhost:8000/digest-auth/20202/username/password/md5"


@name(query)
GET "http://localhost:8000/"
? ram = raju

@name("query2"): query
POST "digest-auth/20202/username/password/md5"


@name("recursive"): recursive
POST "http://localhost:8000/digest-auth/20202/username/password/md5"



@name("args")
@insecure
@clear
POST "http://localhost:8000/digest-auth/20202/username/password/md5"

@name("argsextend") : "args"
POST "http://localhost:8000/digest-auth/20202/username/password/md5"