
POST https://httpbin.org/post

files(
    ('test', '{{filename}}'),
    ('hi','hi2')
)


POST https://httpbin.org/post
fileinput('{{filename}}')



POST https://httpbin.org/post
json({
   'hi':'hi2'
})


POST https://httpbin.org/post
data('<xml>
    <body> hi this is test body</body>
</xml>
', "text/xml")

@name('urlencoded')
POST https://httpbin.org/post
data({
    "test" : ["hai", "bye"],
    "test2": "ram"
})
