
POST http://localhost:8000/post

files(
    ('test', '{{filename}}'),
    ('hi','hi2')
)


POST http://localhost:8000/post
fileinput('{{filename}}')



POST http://localhost:8000/post
json({
   'hi':'hi2'
})


POST http://localhost:8000/post
data('<xml>
    <body> hi this is test body</body>
</xml>
', "text/xml")

@name('urlencoded')
POST http://localhost:8000/post
data({
    "test" : ["hai", "bye"],
    "test2": "ram"
})
