@name("no-password")
GET "https://client.badssl.com/"
certificate(cert="value")


@name("with-key-and-cert")
@clear
@insecure
GET "https://client.badssl.com/"
certificate(cert="value", key="value")


@name("with-p12")
@clear
GET "https://client.badssl.com/"
p12(file="value", password="value")


@name("sample") : with-key-and-cert
GET "sample"


