@name("python_class")
GET https://postman-echo.com/get
> {%

class SampleTest(unittest.TestCase):
    def test_hai(self):
        if client.response.status_code == 200:
            log("working")
        else:
            log(f"not working {client.response.status_code}")
%} python

@name("python_function")
GET https://postman-echo.com/get
> {%

def test_hai():
    if client.response.status_code == 200:
        log("working")
    else:
        log(f"not working {client.response.status_code}")

%} python



@name("javascript")
GET https://postman-echo.com/get
> {%

client.test("check status", function(){
    // checking test and assert
    client.assert(response.status ===200, "status is 200")
})

%} javascript



@name("default_javascript")
GET https://postman-echo.com/get
> {%


client.test("check status", function(){
    // checking test and assert
    client.assert(response.status ===200, "status is 200")
})

%} javascript


@name("python iter")
GET https://postman-echo.com/get
> {%

def test_iter():
    for i in range(10):
        log('something')

%} python
