@name('no-password')
GET https://client.badssl.com/
certificate(cert="{{cert}}")


@name('with-key-and-cert')
@clear
@insecure
GET https://client.badssl.com/
certificate(cert="{{cert}}",key="{{key}}")


@name('with-p12')
@clear
GET https://client.badssl.com/
p12(file="{{p12}}",password="badssl.com")




@name('sample') : "with-key-and-cert"
GET "sample"