POST "https://dothttp.azurewebsites.net"
query("querykey1", "queryvalue1")
header('myhederkey','myheadervalue')
query("querykey2", "queryvalue2")
header('myhederkey2','myheadervalue2')
data('{}')
output('output')