POST "https://dothttp.azurewebsites.net"
query("querykey1", "queryvalue1")
'myhederkey' : 'myheadervalue'
query("querykey2", "queryvalue2")
? ('haha', 'haha')
? 'haha3', 'haha2'
header('myhederkey2','myheadervalue2')
data('{}')
