POST "https://dothttp.azurewebsites.net"
query("querykey1", "queryvalue1 {ram}")
'myhederkey' : 'myheadervalue {ram}'
query("querykey2", "queryvalue2")
? ('haha', '{ram}')
? 'haha3', 'haha2'
header('myhederkey2','myheadervalue2 {ranga}')
data('{}')
