@name("fetch 100 users, skip first 50")
GET https://req.dothttp.dev/user
"Authorization": "Basic dXNlcm5hbWU6cGFzc3dvcmQ="
"content-type": "application/json"
? ("fetch", "100") #
? ("skip", "50")
? projection, name
? projection, org
? projection, location

{
    "payload": {{$randomSlug}}
}
> {%

def test_has_key_in_json():
    assert client.response.status_code == 200, "Non 200 status code"
%}
