@name("dothttp.ranga")
POST https://httpbin.org/post
"myhederkey2": "myheadervalue2"
? ("querykey1", "queryvalue1 {{ram}}")
json({
    "hai": "ram",
    "ram3": null,
    "ranga": 0.0,
    "ram2": [
        {
            "ranga": "{{ram}}"
        }
    ]
})