// some comment
// some comment2
GET http://{{host=localhost:8000}}/get
? dothttp, rocks

POST http://{{host}}/post
? startusing, dothttp


POST http://{{host}}/POST // status 404
? startusing, dothttp

@name(basicauth)
GET http://{{host=localhost:8000}}/get
basicauth('username', 'password')