// some comment
// some comment2
GET https://{{host=httpbin.org}}/get
? dothttp, rocks

POST https://{{host}}/post
? startusing, dothttp


POST https://{{host}}/POST // status 404
? startusing, dothttp

@name(basicauth)
GET https://{{host=httpbin.org}}/get
basicauth('username', 'password')