POST "https://req.dothttp.dev"
json({
    "paylaod": "json"
})


POST "https://req.dothttp.dev"
urlencoded({
    "paylaod": [
        "json"
    ]
})


POST "https://req.dothttp.dev"
text('raw data')


POST "https://req.dothttp.dev"
multipart(
	"raw data" < "other-content-type" ; "text/plain",
	"raw data" < "other-content-type" ; "text/plain"
)


POST "https://req.dothttp.dev"
text('raw data')


POST "https://req.dothttp.dev"
multipart(
	"file" < "/home/prasanth/cedric05/dothttp/test/extensions/commands/payload.http" ; "text/plain"
)


