GET "https://req.dothttp.dev/"
"Host": "req.dothttp.dev"
"Connection": "keep-alive"
"Cache-Control": "max-age=0"
"sec-ch-ua": ""Chromium";v="92", " Not A;Brand";v="99", "Microsoft Edge";v="92""
"sec-ch-ua-mobile": "?0"
"DNT": "1"
"Upgrade-Insecure-Requests": "1"
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4501.0 Safari/537.36 Edg/92.0.891.1"
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
"Sec-Fetch-Site": "none"
"Sec-Fetch-Mode": "navigate"
"Sec-Fetch-User": "?1"
"Sec-Fetch-Dest": "document"
"Accept-Encoding": "gzip, deflate, br"
"Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,en-IN;q=0.7,nl;q=0.6"


GET "https://req.dothttp.dev/favicon.ico"
"Host": "req.dothttp.dev"
"Connection": "keep-alive"
"Pragma": "no-cache"
"Cache-Control": "no-cache"
"sec-ch-ua": ""Chromium";v="92", " Not A;Brand";v="99", "Microsoft Edge";v="92""
"DNT": "1"
"sec-ch-ua-mobile": "?0"
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4501.0 Safari/537.36 Edg/92.0.891.1"
"Accept": "image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"
"Sec-Fetch-Site": "same-origin"
"Sec-Fetch-Mode": "no-cors"
"Sec-Fetch-Dest": "image"
"Referer": "https://req.dothttp.dev/"
"Accept-Encoding": "gzip, deflate, br"
"Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,en-IN;q=0.7,nl;q=0.6"


