@name("text payload")
GET http://localhost:8000/robots.txt
> {%
class TestPayload(unittest.TestCase):
    def test_status(self):
        self.assertEqual(200, client.response.status_code)
        client.properties.set("outputval", client.response.text)

    def test_content_type(self):
        self.assertEqual("application/json", client.response.headers.get('content-type'))


%} python

@name("json_payload")
POST http://localhost:8000/post

json({"token": "secret_token"})
> {%
class TestJsonPayload(unittest.TestCase):
    def test_status(self):
        self.assertEqual(200, client.response.status_code)
        client.properties.set("outputval", client.response.json().get("json", {}).get("token"))
        log("this is sample log")

    def test_headers(self):
        self.assertEqual("application/json", client.response.headers.get('content-type'))



%} python



@name("isEquals check")
POST http://localhost:8000/post

json(
{'simpleKey':'simpleValue',
	"keyWithObjects": [
		"hi",
		"hi2",
		{
			"simpleKey2": "simpleValue2"
		}
	]
}
)
> {%
class TestEquals(unittest.TestCase):
    def test_payload_recursive(self):
        expected = {'simpleKey':'simpleValue',
            "keyWithObjects": [
                "hi",
                "hi2",
                {
                    "simpleKey2": "simpleValue2"
                }
            ]
        }
        self.assertEqual(expected, client.response.json()["json"])
%} python


@name("delete property")
GET http://localhost:8000/robots.txt
// {{setPropertyByfile=sample}}
> {%
def test_1():
    value = client.properties.get("setPropertyByfile")
    log(f"value is `{value}`")
    client.properties.set("setPropertyByfile", "")
%} python


@name("script error")
GET http://localhost:8000/robots.txt
// {{setPropertyByfile=sample}}
> {%
# This will cause an error - intentional for testing
def test_1():
    client.log(client.response.json()["test"]["out"])
%} python



@name("require check")
GET http://localhost:8000/robots.txt
// {{setPropertyByfile=sample}}
> {%
b64 = "SGVsbG8sIFdvcmxkIQ=="
bin_data = base64.b64decode(b64).decode('utf-8')
log(f"value is `{bin_data}`")
%} python