@name('with-key-and-cert')
@insecure
GET https://client.badssl.com/
certificate(cert="{{cert}}",key="{{key}}")



@name('with-key-and-cert')
@clear
GET https://client.badssl.com/
certificate(cert="{{cert}}",key="{{key}}")