//test.http
GET http://localhost:8000/{{var=get}}
? path = "{{var}}"
// curl -X GET 'http://localhost:8000/get?path=get'



POST http://localhost:8000/post
json({
  "firstname": "{{name=john}}",
  "lastname": "{{lastname=doe}}",
  "location": "hyderabad",
// "location": "delhi",
  "full name": "{{name}} {{lastname}}",
})