name: Run Python Tests
on:
  push:
    branches:
      - dev-*
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: |
          sudo apt-get install tar
          poetry config virtualenvs.create false 
          # can use single requirement file referring all three
          poetry install --all-extras --no-root
      - name: Run tests
        run: |
          # current dothttp prints to terminal, which is not good for pytest.
          # although, for test cases, we should ask those who prints to return
          pytest -s --html=report.html --self-contained-html
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html
# benchmark is not working for long time.
# TODO
      # - name: Run benchmark
      #   run: pytest benchmarks/__main__.py --benchmark-json output.json
      # - name: Download previous benchmark data
      #   uses: actions/cache@v1
      #   with:
      #     path: ./cache
      #     key: ${{ runner.os }}-benchmark
      # - name: Store benchmark result
      #   uses: rhysd/github-action-benchmark@v1
      #   with:
      #     name: Python Benchmark with pytest-benchmark
      #     tool: 'pytest'
      #     output-file-path: output.json
      #     alert-threshold: '150%'
      #     fail-on-alert: true
      #     github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      #     comment-on-alert: true